const { gql } = require('apollo-server-express');

module.exports = gql`
  type Restaurant {
    poi_name: String
    operating_hours: [String]
    price_range: String
    street_address_1: String
    street_address_2: String
    city: String
    state: String
    postal_code: String
    country: String
    full_address: String
    neighborhood: String
    latitude: String
    longitude: String
    plus_code: String
    time_zone: String
    operational_status: String
    telephone: String
    email: String
    website: String
    google_place_url: String
    google_place_id: String
    yelp_place_url: String
    yelp_place_id: String
    tripadvisor_place_url: String
    tripadvisor_place_id: String
    opentable_place_url: String
    opentable_place_id: String
    google_rating: String
    google_no_ratings: String
    opentable_rating: String
    opentable_no_ratings: String
    yelp_rating: String
    yelp_no_ratings: String
    tripadvisor_rating: String
    tripadvisor_no_ratings: String
    facebook_rating: String
    facebook_no_ratings: String
    propono_weighted_rating: String
    propono_total_no_ratings: String
    propono_primary_category: [String]
    propono_sub_categories: [String]
    google_mapped_categories: [String]
    opentable_mapped_categories: [String]
    yelp_mapped_categories: [String]
    tripadvisor_mapped_categories: [String]
    atmosphere_romantic: Boolean
    atmosphere_cozy: Boolean
    atmosphere_view: Boolean
    atmosphere_hot_spot: Boolean
    atmosphere_dressy: Boolean
    atmosphere_upscale: Boolean
    atmosphere_casual: Boolean
    diet_healthy: Boolean
    diet_vegetarian_friendly: Boolean
    diet_vegan_options: Boolean
    diet_gluten_free_options: Boolean
    diet_halal: Boolean
    diet_kosher: Boolean
    diet_keto: Boolean
    diet_pescatarian: Boolean
    entertain_full_bar: Boolean
    entertain_beer_wine: Boolean
    entertain_happy_hour: Boolean
    entertain_music: Boolean
    entertain_live_music: Boolean
    entertain_dancing: Boolean
    entertain_karaoke: Boolean
    type_restaurant: Boolean
    type_bakery: Boolean
    type_bars_nightlife: Boolean
    type_coffee_tea: Boolean
    type_dessert: Boolean
    type_specialty_food: Boolean
    general_no_smoking: Boolean
    general_parking_available: Boolean
    general_wheelchair_accessible: Boolean
    # general_wi-fi: Boolean
    general_outdoor_seating: Boolean
    general_dog_friendly: Boolean
    good_kids: Boolean
    good_groups: Boolean
    good_dining_solo: Boolean
    good_working: Boolean
    meals_breakfast: Boolean
    meals_brunch: Boolean
    meals_lunch: Boolean
    meals_dinner: Boolean
    meals_quick_bites: Boolean
    meals_dessert: Boolean
    meals_late_night: Boolean
    payment_credit_cards: Boolean
    payment_discover: Boolean
    payment_mastercard: Boolean
    payment_visa: Boolean
    payment_amex: Boolean
    payment_cash_only: Boolean
    payment_digital: Boolean
    menu_link: String
    reservation_link: String
    order_links: [String]
    poi_description: String
    poi_keywords: [String]
    propono_search_categories: [String]
  }

  type Query {
    restaurants(
      atmosphere_romantic: Boolean
      atmosphere_cozy: Boolean
      atmosphere_view: Boolean
      atmosphere_hot_spot: Boolean
      atmosphere_dressy: Boolean
      atmosphere_upscale: Boolean
      atmosphere_casual: Boolean
      diet_healthy: Boolean
      diet_vegetarian_friendly: Boolean
      diet_vegan_options: Boolean
      diet_gluten_free_options: Boolean
      diet_halal: Boolean
      diet_kosher: Boolean
      diet_keto: Boolean
      diet_pescatarian: Boolean
      entertain_full_bar: Boolean
      entertain_beer_wine: Boolean
      entertain_happy_hour: Boolean
      entertain_music: Boolean
      entertain_live_music: Boolean
      entertain_dancing: Boolean
      entertain_karaoke: Boolean
      type_restaurant: Boolean
      type_bakery: Boolean
      type_bars_nightlife: Boolean
      type_coffee_tea: Boolean
      type_dessert: Boolean
      type_specialty_food: Boolean
      general_no_smoking: Boolean
      general_parking_available: Boolean
      general_wheelchair_accessible: Boolean
      # general_wi-fi: Boolean
      general_outdoor_seating: Boolean
      general_dog_friendly: Boolean
      good_kids: Boolean
      good_groups: Boolean
      good_dining_solo: Boolean
      good_working: Boolean
      meals_breakfast: Boolean
      meals_brunch: Boolean
      meals_lunch: Boolean
      meals_dinner: Boolean
      meals_quick_bites: Boolean
      meals_dessert: Boolean
      meals_late_night: Boolean
      payment_credit_cards: Boolean
      payment_discover: Boolean
      payment_mastercard: Boolean
      payment_visa: Boolean
      payment_amex: Boolean
      payment_cash_only: Boolean
      payment_digital: Boolean
      propono_primary_category: [String]
      propono_sub_categories: [String]
    ): [Restaurant]
  }
`;
